# Generated by Django 5.2.1 on 2026-01-12 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonImpactRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('electricity_units', models.FloatField()),
                ('electricity_co2', models.FloatField()),
                ('transport_mode', models.CharField(max_length=20)),
                ('daily_distance_km', models.FloatField()),
                ('travel_days_per_week', models.PositiveSmallIntegerField()),
                ('transport_co2', models.FloatField()),
                ('cooking_fuel', models.CharField(max_length=20)),
                ('lpg_cylinders_per_month', models.FloatField(blank=True, null=True)),
                ('cooking_co2', models.FloatField()),
                ('uses_ac', models.BooleanField(default=False)),
                ('eats_non_veg', models.BooleanField(default=False)),
                ('uses_plastic_daily', models.BooleanField(default=False)),
                ('lifestyle_co2', models.FloatField()),
                ('total_co2', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
