# Generated by Django 5.2.1 on 2026-01-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_impact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbonimpactrecord',
            name='daily_distance_km',
        ),
        migrations.RemoveField(
            model_name='carbonimpactrecord',
            name='transport_mode',
        ),
        migrations.RemoveField(
            model_name='carbonimpactrecord',
            name='travel_days_per_week',
        ),
    ]
