# Generated by Django 5.2.1 on 2025-05-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100, unique=True)),
                ('carbon_emission_factor', models.FloatField()),
                ('default_proportion', models.FloatField()),
                ('toxicity', models.FloatField()),
                ('biodegradability', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('product_link', models.URLField()),
                ('volume', models.CharField(max_length=50)),
                ('chemical_free', models.BooleanField()),
                ('packaging_type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('in_stock', models.BooleanField()),
                ('return_period', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('ecoscore', models.FloatField()),
                ('carbon_footprint', models.FloatField()),
                ('toxicity_score', models.FloatField()),
                ('biodegradability_score', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('ingredients', models.ManyToManyField(to='accounts.ingredient')),
            ],
        ),
    ]
