# Generated by Django 5.2.1 on 2025-05-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients_raw',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
