# Generated by Django 5.2.1 on 2026-01-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(help_text='EAN / UPC barcode number', max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('ingredients', models.TextField()),
                ('ecoscore', models.FloatField()),
                ('carbon_footprint', models.FloatField()),
                ('toxicity', models.FloatField()),
                ('biodegradability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Generic product name (e.g. lip balm, shampoo)', max_length=255, unique=True)),
                ('ingredients', models.TextField(help_text='Complete ingredient list')),
            ],
        ),
    ]
